import linecache
import random
# Create account function :)


def createaccount():
    nameline = linecache.getline("Accounts.txt", 3).split()
    name = input("Enter name:")
    while len(name) < 6:
        name = input("invalid username, please try again :")
    while name in nameline:
        name = input("this name already excists, try again :")
    else:
        nameline = list(nameline)
        nameline.append(name)
        nameline = str(nameline)
        nameline = nameline.replace("[", "")
        nameline = nameline.replace("'", "")
        nameline = nameline.replace(",", "")
        nameline = nameline.replace("]", "")
        print(f"welcome,{name}")
    acc = input("Enter ACC:")
    while not(acc.endswith("@gmail.com")) or len(acc) < 15:
        acc = input("invalid email, try again :")
    else:
        print("")
    accline = linecache.getline("Accounts.txt", 1).split()
    while acc in accline:
        acc = input("Already exists,Try another one!")
    else:
        accline = list(accline)
        accline.append(acc)
        accline = str(accline)
        accline = accline.replace("[", "")
        accline = accline.replace("'", "")
        accline = accline.replace(",", "")
        accline = accline.replace("]", "")
    passs = input("Enter PASS:")
    linepass = linecache.getline("Accounts.txt", 2).split()
    while len(passs) > 14 or len(passs) < 6:
        passs = input("this password is not proper, try again :")

    else:

        linepass = list(linepass)
        linepass.append(passs)
        linepass = str(linepass)
        linepass = linepass.replace("[", "")
        linepass = linepass.replace("'", "")
        linepass = linepass.replace(",", "")
        linepass = linepass.replace("]", "")
    number = input("Enter Number")
    while not (number.startswith("012") or number.startswith("011") or number.startswith("010") or number.startswith("015")) or len(number) != 11:
        number = input("try again")
    phoneline = linecache.getline("Accounts.txt", 4).split()
    while number in phoneline:
        number = input("Existed!,Try another one:")
    else:
        phoneline = list(phoneline)
        phoneline.append(number)
        phoneline = str(phoneline)
        phoneline = phoneline.replace("[", "")
        phoneline = phoneline.replace("'", "")
        phoneline = phoneline.replace(",", "")
        phoneline = phoneline.replace("]", "")

    address = input("do you want to enter your addres now:")
    if address == "yes":
        location(input("Enter City:"), input("Enter area:"), input("Enter street:(landmark(optional))"), input("Enter building:"), input("Enter Floor:"), input("Enter apartment:"))
    elif address == "no":
        print(f"{address} address added")
    file_w = open("Accounts.txt", "w")
    file_w.write(accline)
    file_w.write("\n")
    file_w.write(linepass)
    file_w.write("\n")
    file_w.write(nameline)
    file_w.write("\n")
    file_w.write(str(phoneline))


#createaccount()
# Read Account Function


def readaccount(acc_in, pass_in):
    checker = False
    accountline = linecache.getline("Accounts.txt", 1).split()
    linepass = linecache.getline("Accounts.txt", 2).split()
    while checker is False:
        if acc_in in accountline:
            acccheck = accountline.index(acc_in)
            if linepass.__contains__(pass_in):
                passcheck = linepass.index(pass_in)
                if passcheck == acccheck:
                    checker = True
                else:
                    pass_in = input("Wrong Password,please try again:")
            else:
                pass_in = input("Wrong Password,please try again:")
        else:
            acc_in = input("Account is not saved.try again:")
    else:
        print("Signed in!")


#readaccount(input("Enter Mail:"), input("Enter Password:"))
# Forget Password function


def forgetpassword(email):
    emailreader = linecache.getline("Accounts.txt", 1).split()
    if email not in emailreader:
        print("Not valid")
    else:
        emailindex = linecache.getline("Accounts.txt", 1).split().index(email)
        newpass = input("Enter New Password")
        while len(newpass) < 6:
            newpass = input("Enter Longer Password:")
        emailline = linecache.getline("Accounts.txt", 1).split()
        indexmail = int(emailindex)
        passline = linecache.getline("Accounts.txt", 2).split()
        passline = list(passline)
        passline.pop(indexmail)
        passline.insert(indexmail, newpass)
        emailline = str(emailline)
        passline = str(passline)
        passline = passline.replace("[", "")
        passline = passline.replace("'", "")
        passline = passline.replace(",", "")
        passline = passline.replace("]", "")
        emailline = emailline.replace("[", "")
        emailline = emailline.replace("'", "")
        emailline = emailline.replace(",", "")
        emailline = emailline.replace("]", "")
        nameline = linecache.getline("Accounts.txt", 3).split()
        nameline = list(nameline)
        nameline = str(nameline)
        nameline = nameline.replace("[", "")
        nameline = nameline.replace("'", "")
        nameline = nameline.replace(",", "")
        nameline = nameline.replace("]", "")
        phoneline = linecache.getline("Accounts.txt", 4).split()
        phoneline = list(phoneline)

        phoneline = str(phoneline)
        phoneline = phoneline.replace("[", "")
        phoneline = phoneline.replace("'", "")
        phoneline = phoneline.replace(",", "")
        phoneline = phoneline.replace("]", "")
        file_w = open("Accounts.txt", "w")
        file_w.write(emailline)
        file_w.write("\n")
        file_w.write(passline)
        file_w.write("\n")
        file_w.write(nameline)
        file_w.write("\n")
        file_w.write(str(phoneline))
        print("Password reset done!")


#forgetpassword(input("Enter email"))

# Visa Data :)


def visadata(visa_in):
    while not (len(visa_in) == 16 and (visa_in.isdigit())):
        visa_in = input("Must Be 16-digit number, please try again:")
    else:
        cardname = input("Enter card holder name:")
        while not(cardname.isalpha()):
            cardname = input("Enter Valid Name:")
        expdatemonth = input("Enter Expiry date(Month):")
        while not (expdatemonth.isdigit()) or int(expdatemonth) > 12 or int(expdatemonth) < 1:
            expdatemonth = input("Check your expiry month")
        expdateyear = input("Enter Expiry dat(Year):")
        while not(expdateyear.isdigit()) or int(expdateyear) < 2023:
            expdateyear = input("Check your expiry year:")
        cvv = input("Enter CVV:")
        collected = (visa_in + "," + cardname + "," + expdatemonth + "/"+expdateyear+"," + cvv)
        while not (len(cvv) == 3 and cvv.isdigit()):
            cvv = input("Enter valid CVV from 3-digits:")
        else:
            file = open("Visa.txt", "a")
            file_r = open("Visa.txt", "r")
            existcheck = file_r.read()
            if collected not in existcheck:
                file.write(visa_in)
                file.write(",")
                file.write(cardname)
                file.write(",")
                file.write(expdatemonth)
                file.write("/")
                file.write(expdateyear)
                file.write(",")
                file.write(cvv)
                file.write("\n")
                print("Data saved and payment done")
            else:
                print("Payment Done!")
            file.close()
            file_r.close()


#visadata(input("Enter 16-digit Number:"))
# Sorted by brand


def lapsortedby(brand):
    open("Models.txt", "r")
    if brand == "Dell":
        priceline = linecache.getline("Models.txt", 1).split("/")
        priceline2 = linecache.getline("Models.txt", 2).split("/")
        print(priceline, "\n", priceline2)
    elif brand == "HP":
        priceline = linecache.getline("Models.txt", 3).split("/")
        priceline2 = linecache.getline("Models.txt", 4).split("/")
        print(priceline, "\n", priceline2)
    elif brand == "Lenovo":
        priceline = linecache.getline("Models.txt", 5).split("/")
        priceline2 = linecache.getline("Models.txt", 6).split("/")
        print(priceline, "\n", priceline2)
    elif brand == "Acer":
        priceline = linecache.getline("Models.txt", 7).split("/")
        priceline2 = linecache.getline("Models.txt", 8).split("/")
        print(priceline, "\n", priceline2)
    elif brand == "Asus":
        priceline = linecache.getline("Models.txt", 9).split("/")
        priceline2 = linecache.getline("Models.txt", 10).split("/")
        print(priceline, "\n", priceline2)
    elif brand == "MSI":
        priceline = linecache.getline("Models.txt", 13).split("/")
        priceline2 = linecache.getline("Models.txt", 14).split("/")
        print(priceline, "\n", priceline2)
    elif brand == "Apple":
        priceline = linecache.getline("Models.txt", 11).split("/")
        print(priceline)
    elif brand == "Huawei":
        priceline = linecache.getline("Models.txt", 12).split("/")
        print(priceline)
    elif brand == "Microsoft":
        priceline = linecache.getline("Models.txt", 15).split("/")
        print(priceline)


#lapsortedby(input("Enter Brand:"))


def laprandom():
    randomline = linecache.getline("Models.txt", 16).split()
    randomlist = random.sample(randomline, k=62)
    print(randomlist)


#laprandom()


def random_list():
    open("Project[accessories].txt", "r")
    acssline11 = linecache.getline("Project[accessories].txt", 7).split()
    randomsorted = random.sample(acssline11, k=41)
    print(randomsorted)


#random_list()


def accs_sortedby(item):
    open("Project[accessories].txt", "r")
    if item == "bags":
        priceline = linecache.getline("Project[accessories].txt", 1).split(",")
        print(priceline, "\n")
    elif item == "mouses":
        priceline = linecache.getline("Project[accessories].txt", 3).split(",")
        print(priceline, "\n")
    elif item == "skins":
        priceline = linecache.getline("Project[accessories].txt", 2).split(",")
        print(priceline, "\n")
    elif item == "chargers":
        priceline = linecache.getline("Project[accessories].txt", 4).split(",")
        print(priceline, "\n")
    elif item == "laptop tables":
        priceline = linecache.getline("Project[accessories].txt", 5).split(",")
        print(priceline, "\n")
    elif item == "stand holders":
        priceline = linecache.getline("Project[accessories].txt", 6).split(",")
        print(priceline, ",\n")


#accs_sortedby(input("Enter an item :"))


def location(city, area, street, building, floor, apartment):
    print("Your order will be delivered to:", city, "city,", area, ",", street, "street,", "Building", building, ",floor number", floor, ",apartment number", apartment)
    file_a = open("Location.txt", "a")
    file_a.write(city)
    file_a.write(",")
    file_a.write(area)
    file_a.write(",")
    file_a.write(street)
    file_a.write(",")
    file_a.write(building)
    file_a.write(",")
    file_a.write(floor)
    file_a.write(",")
    file_a.write(apartment)
    file_a.write("\n")


#location(input("Enter City:"), input("Enter area:"), input("Enter street:(landmark(optional))"), input("Enter building:"), input("Enter Floor:"), input("Enter apartment:"))


def seller(item):
    accsfile = open("Project[accessories].txt", "r")
    e1 = linecache.getline("Project[accessories].txt", 1).split()
    e2 = linecache.getline("Project[accessories].txt", 2).split()
    e3 = linecache.getline("Project[accessories].txt", 3).split()
    e4 = linecache.getline("Project[accessories].txt", 4).split()
    e5 = linecache.getline("Project[accessories].txt", 5).split()
    e6 = linecache.getline("Project[accessories].txt", 6).split()
    m1 = linecache.getline("Models.txt", 1).split()
    m2 = linecache.getline("Models.txt", 2).split()
    m3 = linecache.getline("Models.txt", 4).split()
    m4 = linecache.getline("Models.txt", 4).split()
    m5 = linecache.getline("Models.txt", 5).split()
    m6 = linecache.getline("Models.txt", 6).split()
    m7 = linecache.getline("Models.txt", 7).split()
    m8 = linecache.getline("Models.txt", 8).split()
    m9 = linecache.getline("Models.txt", 9).split()
    m10 = linecache.getline("Models.txt", 10).split()
    m11 = linecache.getline("Models.txt", 11).split()
    m12 = linecache.getline("Models.txt", 12).split()
    m13 = linecache.getline("Models.txt", 13).split()
    m14 = linecache.getline("Models.txt", 14).split()
    m15 = linecache.getline("Models.txt", 15).split()
    invertory = input("product :")

    if item == "Dell Gaming":
        m1 = list(m1)
        m1.append(invertory)
        e = open("Models.txt", "w")
        m1 = str(m1)
        m1 = m1.replace("[", "")
        m1 = m1.replace("]", "")
        m1 = m1.replace("'", "")
        m1 = m1.replace(",", "")
        m2 = str(m2)
        m2 = m2.replace("[", "")
        m2 = m2.replace("]", "")
        m2 = m2.replace("'", "")
        m2 = m2.replace(",", "")
        m4 = str(m4)
        m4 = m4.replace("[", "")
        m4 = m4.replace("]", "")
        m4 = m4.replace("'", "")
        m4 = m4.replace(",", "")
        m5 = str(m5)
        m5 = m5.replace("[", "")
        m5 = m5.replace("]", "")
        m5 = m5.replace("'", "")
        m5 = m5.replace(",", "")
        m6 = str(m6)
        m6 = m6.replace("[", "")
        m6 = m6.replace("]", "")
        m6 = m6.replace("'", "")
        m6 = m6.replace(",", "")
        m7 = str(m7)
        m7 = m7.replace("[", "")
        m7 = m7.replace("]", "")
        m7 = m7.replace("'", "")
        m7 = m7.replace(",", "")
        m8 = str(m8)
        m8 = m8.replace("[", "")
        m8 = m8.replace("]", "")
        m8 = m8.replace("'", "")
        m8 = m8.replace(",", "")
        m9 = str(m9)
        m9 = m9.replace("[", "")
        m9 = m9.replace("]", "")
        m9 = m9.replace("'", "")
        m9 = m9.replace(",", "")
        m10 = str(m10)
        m10 = m10.replace("[", "")
        m10 = m10.replace("]", "")
        m10 = m10.replace("'", "")
        m10 = m10.replace(",", "")
        m11 = str(m11)
        m11 = m11.replace("[", "")
        m11 = m11.replace("]", "")
        m11 = m11.replace("'", "")
        m11 = m11.replace(",", "")
        m12 = str(m12)
        m12 = m12.replace("[", "")
        m12 = m12.replace("]", "")
        m12 = m12.replace("'", "")
        m12 = m12.replace(",", "")
        m13 = str(m13)
        m13 = m13.replace("[", "")
        m13 = m13.replace("]", "")
        m13 = m13.replace("'", "")
        m13 = m13.replace(",", "")
        m14 = str(m14)
        m14 = m14.replace("[", "")
        m14 = m14.replace("]", "")
        m14 = m14.replace("'", "")
        m14 = m14.replace(",", "")
        m15 = str(m15)
        m15 = m15.replace("[", "")
        m15 = m15.replace("]", "")
        m15 = m15.replace("'", "")
        m15 = m15.replace(",", "")
        m3 = str(m3)
        m3 = m3.replace("[", "")
        m3 = m3.replace("]", "")
        m3 = m3.replace("'", "")
        m3 = m3.replace(",", "")
        e.write(m1)
        e.write("\n")
        e.write(m2)
        e.write("\n")
        e.write(m3)
        e.write("\n")
        e.write(m4)
        e.write("\n")
        e.write(m5)
        e.write("\n")
        e.write(m6)
        e.write("\n")
        e.write(m7)
        e.write("\n")
        e.write(m8)
        e.write("\n")
        e.write(m9)
        e.write("\n")
        e.write(m10)
        e.write("\n")
        e.write(m11)
        e.write("\n")
        e.write(m12)
        e.write("\n")
        e.write(m13)
        e.write("\n")
        e.write(m14)
        e.write("\n")
        e.write(m15)
        e.close()
    elif item == "Dell Business":
        m2 = list(m2)
        m2.append(invertory)
        e = open("Models.txt", "w")
        m1 = str(m1)
        m1 = m1.replace("[", "")
        m1 = m1.replace("]", "")
        m1 = m1.replace("'", "")
        m1 = m1.replace(",", "")
        m2 = str(m2)
        m2 = m2.replace("[", "")
        m2 = m2.replace("]", "")
        m2 = m2.replace("'", "")
        m2 = m2.replace(",", "")
        m4 = str(m4)
        m4 = m4.replace("[", "")
        m4 = m4.replace("]", "")
        m4 = m4.replace("'", "")
        m4 = m4.replace(",", "")
        m5 = str(m5)
        m5 = m5.replace("[", "")
        m5 = m5.replace("]", "")
        m5 = m5.replace("'", "")
        m5 = m5.replace(",", "")
        m6 = str(m6)
        m6 = m6.replace("[", "")
        m6 = m6.replace("]", "")
        m6 = m6.replace("'", "")
        m6 = m6.replace(",", "")
        m7 = str(m7)
        m7 = m7.replace("[", "")
        m7 = m7.replace("]", "")
        m7 = m7.replace("'", "")
        m7 = m7.replace(",", "")
        m8 = str(m8)
        m8 = m8.replace("[", "")
        m8 = m8.replace("]", "")
        m8 = m8.replace("'", "")
        m8 = m8.replace(",", "")
        m9 = str(m9)
        m9 = m9.replace("[", "")
        m9 = m9.replace("]", "")
        m9 = m9.replace("'", "")
        m9 = m9.replace(",", "")
        m10 = str(m10)
        m10 = m10.replace("[", "")
        m10 = m10.replace("]", "")
        m10 = m10.replace("'", "")
        m10 = m10.replace(",", "")
        m11 = str(m11)
        m11 = m11.replace("[", "")
        m11 = m11.replace("]", "")
        m11 = m11.replace("'", "")
        m11 = m11.replace(",", "")
        m12 = str(m12)
        m12 = m12.replace("[", "")
        m12 = m12.replace("]", "")
        m12 = m12.replace("'", "")
        m12 = m12.replace(",", "")
        m13 = str(m13)
        m13 = m13.replace("[", "")
        m13 = m13.replace("]", "")
        m13 = m13.replace("'", "")
        m13 = m13.replace(",", "")
        m14 = str(m14)
        m14 = m14.replace("[", "")
        m14 = m14.replace("]", "")
        m14 = m14.replace("'", "")
        m14 = m14.replace(",", "")
        m15 = str(m15)
        m15 = m15.replace("[", "")
        m15 = m15.replace("]", "")
        m15 = m15.replace("'", "")
        m15 = m15.replace(",", "")
        m3 = str(m3)
        m3 = m3.replace("[", "")
        m3 = m3.replace("]", "")
        m3 = m3.replace("'", "")
        m3 = m3.replace(",", "")
        e.write(m1)
        e.write("\n")
        e.write(m2)
        e.write("\n")
        e.write(m3)
        e.write("\n")
        e.write(m4)
        e.write("\n")
        e.write(m5)
        e.write("\n")
        e.write(m6)
        e.write("\n")
        e.write(m7)
        e.write("\n")
        e.write(m8)
        e.write("\n")
        e.write(m9)
        e.write("\n")
        e.write(m10)
        e.write("\n")
        e.write(m11)
        e.write("\n")
        e.write(m12)
        e.write("\n")
        e.write(m13)
        e.write("\n")
        e.write(m14)
        e.write("\n")
        e.write(m15)
        e.close()
    elif item == "HP Gaming":
        m3 = list(m3)
        m3.append(invertory)
        e = open("Models.txt", "w")
        m1 = str(m1)
        m1 = m1.replace("[", "")
        m1 = m1.replace("]", "")
        m1 = m1.replace("'", "")
        m1 = m1.replace(",", "")
        m2 = str(m2)
        m2 = m2.replace("[", "")
        m2 = m2.replace("]", "")
        m2 = m2.replace("'", "")
        m2 = m2.replace(",", "")
        m4 = str(m4)
        m4 = m4.replace("[", "")
        m4 = m4.replace("]", "")
        m4 = m4.replace("'", "")
        m4 = m4.replace(",", "")
        m5 = str(m5)
        m5 = m5.replace("[", "")
        m5 = m5.replace("]", "")
        m5 = m5.replace("'", "")
        m5 = m5.replace(",", "")
        m6 = str(m6)
        m6 = m6.replace("[", "")
        m6 = m6.replace("]", "")
        m6 = m6.replace("'", "")
        m6 = m6.replace(",", "")
        m7 = str(m7)
        m7 = m7.replace("[", "")
        m7 = m7.replace("]", "")
        m7 = m7.replace("'", "")
        m7 = m7.replace(",", "")
        m8 = str(m8)
        m8 = m8.replace("[", "")
        m8 = m8.replace("]", "")
        m8 = m8.replace("'", "")
        m8 = m8.replace(",", "")
        m9 = str(m9)
        m9 = m9.replace("[", "")
        m9 = m9.replace("]", "")
        m9 = m9.replace("'", "")
        m9 = m9.replace(",", "")
        m10 = str(m10)
        m10 = m10.replace("[", "")
        m10 = m10.replace("]", "")
        m10 = m10.replace("'", "")
        m10 = m10.replace(",", "")
        m11 = str(m11)
        m11 = m11.replace("[", "")
        m11 = m11.replace("]", "")
        m11 = m11.replace("'", "")
        m11 = m11.replace(",", "")
        m12 = str(m12)
        m12 = m12.replace("[", "")
        m12 = m12.replace("]", "")
        m12 = m12.replace("'", "")
        m12 = m12.replace(",", "")
        m13 = str(m13)
        m13 = m13.replace("[", "")
        m13 = m13.replace("]", "")
        m13 = m13.replace("'", "")
        m13 = m13.replace(",", "")
        m14 = str(m14)
        m14 = m14.replace("[", "")
        m14 = m14.replace("]", "")
        m14 = m14.replace("'", "")
        m14 = m14.replace(",", "")
        m15 = str(m15)
        m15 = m15.replace("[", "")
        m15 = m15.replace("]", "")
        m15 = m15.replace("'", "")
        m15 = m15.replace(",", "")
        m3 = str(m3)
        m3 = m3.replace("[", "")
        m3 = m3.replace("]", "")
        m3 = m3.replace("'", "")
        m3 = m3.replace(",", "")
        e.write(m1)
        e.write("\n")
        e.write(m2)
        e.write("\n")
        e.write(m3)
        e.write("\n")
        e.write(m4)
        e.write("\n")
        e.write(m5)
        e.write("\n")
        e.write(m6)
        e.write("\n")
        e.write(m7)
        e.write("\n")
        e.write(m8)
        e.write("\n")
        e.write(m9)
        e.write("\n")
        e.write(m10)
        e.write("\n")
        e.write(m11)
        e.write("\n")
        e.write(m12)
        e.write("\n")
        e.write(m13)
        e.write("\n")
        e.write(m14)
        e.write("\n")
        e.write(m15)
        e.close()
    elif item == "HP Business":
        m4 = list(m4)
        m4.append(invertory)
        e = open("Models.txt", "w")
        m1 = str(m1)
        m1 = m1.replace("[", "")
        m1 = m1.replace("]", "")
        m1 = m1.replace("'", "")
        m1 = m1.replace(",", "")
        m2 = str(m2)
        m2 = m2.replace("[", "")
        m2 = m2.replace("]", "")
        m2 = m2.replace("'", "")
        m2 = m2.replace(",", "")
        m4 = str(m4)
        m4 = m4.replace("[", "")
        m4 = m4.replace("]", "")
        m4 = m4.replace("'", "")
        m4 = m4.replace(",", "")
        m5 = str(m5)
        m5 = m5.replace("[", "")
        m5 = m5.replace("]", "")
        m5 = m5.replace("'", "")
        m5 = m5.replace(",", "")
        m6 = str(m6)
        m6 = m6.replace("[", "")
        m6 = m6.replace("]", "")
        m6 = m6.replace("'", "")
        m6 = m6.replace(",", "")
        m7 = str(m7)
        m7 = m7.replace("[", "")
        m7 = m7.replace("]", "")
        m7 = m7.replace("'", "")
        m7 = m7.replace(",", "")
        m8 = str(m8)
        m8 = m8.replace("[", "")
        m8 = m8.replace("]", "")
        m8 = m8.replace("'", "")
        m8 = m8.replace(",", "")
        m9 = str(m9)
        m9 = m9.replace("[", "")
        m9 = m9.replace("]", "")
        m9 = m9.replace("'", "")
        m9 = m9.replace(",", "")
        m10 = str(m10)
        m10 = m10.replace("[", "")
        m10 = m10.replace("]", "")
        m10 = m10.replace("'", "")
        m10 = m10.replace(",", "")
        m11 = str(m11)
        m11 = m11.replace("[", "")
        m11 = m11.replace("]", "")
        m11 = m11.replace("'", "")
        m11 = m11.replace(",", "")
        m12 = str(m12)
        m12 = m12.replace("[", "")
        m12 = m12.replace("]", "")
        m12 = m12.replace("'", "")
        m12 = m12.replace(",", "")
        m13 = str(m13)
        m13 = m13.replace("[", "")
        m13 = m13.replace("]", "")
        m13 = m13.replace("'", "")
        m13 = m13.replace(",", "")
        m14 = str(m14)
        m14 = m14.replace("[", "")
        m14 = m14.replace("]", "")
        m14 = m14.replace("'", "")
        m14 = m14.replace(",", "")
        m15 = str(m15)
        m15 = m15.replace("[", "")
        m15 = m15.replace("]", "")
        m15 = m15.replace("'", "")
        m15 = m15.replace(",", "")
        m3 = str(m3)
        m3 = m3.replace("[", "")
        m3 = m3.replace("]", "")
        m3 = m3.replace("'", "")
        m3 = m3.replace(",", "")
        e.write(m1)
        e.write("\n")
        e.write(m2)
        e.write("\n")
        e.write(m3)
        e.write("\n")
        e.write(m4)
        e.write("\n")
        e.write(m5)
        e.write("\n")
        e.write(m6)
        e.write("\n")
        e.write(m7)
        e.write("\n")
        e.write(m8)
        e.write("\n")
        e.write(m9)
        e.write("\n")
        e.write(m10)
        e.write("\n")
        e.write(m11)
        e.write("\n")
        e.write(m12)
        e.write("\n")
        e.write(m13)
        e.write("\n")
        e.write(m14)
        e.write("\n")
        e.write(m15)
        e.close()
    elif item == "Lenovo Gaming":
        m5 = list(m5)
        m5.append(invertory)
        e = open("Models.txt", "w")
        m1 = str(m1)
        m1 = m1.replace("[", "")
        m1 = m1.replace("]", "")
        m1 = m1.replace("'", "")
        m1 = m1.replace(",", "")
        m2 = str(m2)
        m2 = m2.replace("[", "")
        m2 = m2.replace("]", "")
        m2 = m2.replace("'", "")
        m2 = m2.replace(",", "")
        m4 = str(m4)
        m4 = m4.replace("[", "")
        m4 = m4.replace("]", "")
        m4 = m4.replace("'", "")
        m4 = m4.replace(",", "")
        m5 = str(m5)
        m5 = m5.replace("[", "")
        m5 = m5.replace("]", "")
        m5 = m5.replace("'", "")
        m5 = m5.replace(",", "")
        m6 = str(m6)
        m6 = m6.replace("[", "")
        m6 = m6.replace("]", "")
        m6 = m6.replace("'", "")
        m6 = m6.replace(",", "")
        m7 = str(m7)
        m7 = m7.replace("[", "")
        m7 = m7.replace("]", "")
        m7 = m7.replace("'", "")
        m7 = m7.replace(",", "")
        m8 = str(m8)
        m8 = m8.replace("[", "")
        m8 = m8.replace("]", "")
        m8 = m8.replace("'", "")
        m8 = m8.replace(",", "")
        m9 = str(m9)
        m9 = m9.replace("[", "")
        m9 = m9.replace("]", "")
        m9 = m9.replace("'", "")
        m9 = m9.replace(",", "")
        m10 = str(m10)
        m10 = m10.replace("[", "")
        m10 = m10.replace("]", "")
        m10 = m10.replace("'", "")
        m10 = m10.replace(",", "")
        m11 = str(m11)
        m11 = m11.replace("[", "")
        m11 = m11.replace("]", "")
        m11 = m11.replace("'", "")
        m11 = m11.replace(",", "")
        m12 = str(m12)
        m12 = m12.replace("[", "")
        m12 = m12.replace("]", "")
        m12 = m12.replace("'", "")
        m12 = m12.replace(",", "")
        m13 = str(m13)
        m13 = m13.replace("[", "")
        m13 = m13.replace("]", "")
        m13 = m13.replace("'", "")
        m13 = m13.replace(",", "")
        m14 = str(m14)
        m14 = m14.replace("[", "")
        m14 = m14.replace("]", "")
        m14 = m14.replace("'", "")
        m14 = m14.replace(",", "")
        m15 = str(m15)
        m15 = m15.replace("[", "")
        m15 = m15.replace("]", "")
        m15 = m15.replace("'", "")
        m15 = m15.replace(",", "")
        m3 = str(m3)
        m3 = m3.replace("[", "")
        m3 = m3.replace("]", "")
        m3 = m3.replace("'", "")
        m3 = m3.replace(",", "")
        e.write(m1)
        e.write("\n")
        e.write(m2)
        e.write("\n")
        e.write(m3)
        e.write("\n")
        e.write(m4)
        e.write("\n")
        e.write(m5)
        e.write("\n")
        e.write(m6)
        e.write("\n")
        e.write(m7)
        e.write("\n")
        e.write(m8)
        e.write("\n")
        e.write(m9)
        e.write("\n")
        e.write(m10)
        e.write("\n")
        e.write(m11)
        e.write("\n")
        e.write(m12)
        e.write("\n")
        e.write(m13)
        e.write("\n")
        e.write(m14)
        e.write("\n")
        e.write(m15)
        e.close()
    elif item == "Lenovo Business":
        m6 = list(m6)
        m6.append(invertory)
        e = open("Models.txt", "w")
        m1 = str(m1)
        m1 = m1.replace("[", "")
        m1 = m1.replace("]", "")
        m1 = m1.replace("'", "")
        m1 = m1.replace(",", "")
        m2 = str(m2)
        m2 = m2.replace("[", "")
        m2 = m2.replace("]", "")
        m2 = m2.replace("'", "")
        m2 = m2.replace(",", "")
        m4 = str(m4)
        m4 = m4.replace("[", "")
        m4 = m4.replace("]", "")
        m4 = m4.replace("'", "")
        m4 = m4.replace(",", "")
        m5 = str(m5)
        m5 = m5.replace("[", "")
        m5 = m5.replace("]", "")
        m5 = m5.replace("'", "")
        m5 = m5.replace(",", "")
        m6 = str(m6)
        m6 = m6.replace("[", "")
        m6 = m6.replace("]", "")
        m6 = m6.replace("'", "")
        m6 = m6.replace(",", "")
        m7 = str(m7)
        m7 = m7.replace("[", "")
        m7 = m7.replace("]", "")
        m7 = m7.replace("'", "")
        m7 = m7.replace(",", "")
        m8 = str(m8)
        m8 = m8.replace("[", "")
        m8 = m8.replace("]", "")
        m8 = m8.replace("'", "")
        m8 = m8.replace(",", "")
        m9 = str(m9)
        m9 = m9.replace("[", "")
        m9 = m9.replace("]", "")
        m9 = m9.replace("'", "")
        m9 = m9.replace(",", "")
        m10 = str(m10)
        m10 = m10.replace("[", "")
        m10 = m10.replace("]", "")
        m10 = m10.replace("'", "")
        m10 = m10.replace(",", "")
        m11 = str(m11)
        m11 = m11.replace("[", "")
        m11 = m11.replace("]", "")
        m11 = m11.replace("'", "")
        m11 = m11.replace(",", "")
        m12 = str(m12)
        m12 = m12.replace("[", "")
        m12 = m12.replace("]", "")
        m12 = m12.replace("'", "")
        m12 = m12.replace(",", "")
        m13 = str(m13)
        m13 = m13.replace("[", "")
        m13 = m13.replace("]", "")
        m13 = m13.replace("'", "")
        m13 = m13.replace(",", "")
        m14 = str(m14)
        m14 = m14.replace("[", "")
        m14 = m14.replace("]", "")
        m14 = m14.replace("'", "")
        m14 = m14.replace(",", "")
        m15 = str(m15)
        m15 = m15.replace("[", "")
        m15 = m15.replace("]", "")
        m15 = m15.replace("'", "")
        m15 = m15.replace(",", "")
        m3 = str(m3)
        m3 = m3.replace("[", "")
        m3 = m3.replace("]", "")
        m3 = m3.replace("'", "")
        m3 = m3.replace(",", "")
        e.write(m1)
        e.write("\n")
        e.write(m2)
        e.write("\n")
        e.write(m3)
        e.write("\n")
        e.write(m4)
        e.write("\n")
        e.write(m5)
        e.write("\n")
        e.write(m6)
        e.write("\n")
        e.write(m7)
        e.write("\n")
        e.write(m8)
        e.write("\n")
        e.write(m9)
        e.write("\n")
        e.write(m10)
        e.write("\n")
        e.write(m11)
        e.write("\n")
        e.write(m12)
        e.write("\n")
        e.write(m13)
        e.write("\n")
        e.write(m14)
        e.write("\n")
        e.write(m15)
        e.close()
    elif item == "Acer Gaming":
        m7 = list(m7)
        m7.append(invertory)
        e = open("Models.txt", "w")
        m1 = str(m1)
        m1 = m1.replace("[", "")
        m1 = m1.replace("]", "")
        m1 = m1.replace("'", "")
        m1 = m1.replace(",", "")
        m2 = str(m2)
        m2 = m2.replace("[", "")
        m2 = m2.replace("]", "")
        m2 = m2.replace("'", "")
        m2 = m2.replace(",", "")
        m4 = str(m4)
        m4 = m4.replace("[", "")
        m4 = m4.replace("]", "")
        m4 = m4.replace("'", "")
        m4 = m4.replace(",", "")
        m5 = str(m5)
        m5 = m5.replace("[", "")
        m5 = m5.replace("]", "")
        m5 = m5.replace("'", "")
        m5 = m5.replace(",", "")
        m6 = str(m6)
        m6 = m6.replace("[", "")
        m6 = m6.replace("]", "")
        m6 = m6.replace("'", "")
        m6 = m6.replace(",", "")
        m7 = str(m7)
        m7 = m7.replace("[", "")
        m7 = m7.replace("]", "")
        m7 = m7.replace("'", "")
        m7 = m7.replace(",", "")
        m8 = str(m8)
        m8 = m8.replace("[", "")
        m8 = m8.replace("]", "")
        m8 = m8.replace("'", "")
        m8 = m8.replace(",", "")
        m9 = str(m9)
        m9 = m9.replace("[", "")
        m9 = m9.replace("]", "")
        m9 = m9.replace("'", "")
        m9 = m9.replace(",", "")
        m10 = str(m10)
        m10 = m10.replace("[", "")
        m10 = m10.replace("]", "")
        m10 = m10.replace("'", "")
        m10 = m10.replace(",", "")
        m11 = str(m11)
        m11 = m11.replace("[", "")
        m11 = m11.replace("]", "")
        m11 = m11.replace("'", "")
        m11 = m11.replace(",", "")
        m12 = str(m12)
        m12 = m12.replace("[", "")
        m12 = m12.replace("]", "")
        m12 = m12.replace("'", "")
        m12 = m12.replace(",", "")
        m13 = str(m13)
        m13 = m13.replace("[", "")
        m13 = m13.replace("]", "")
        m13 = m13.replace("'", "")
        m13 = m13.replace(",", "")
        m14 = str(m14)
        m14 = m14.replace("[", "")
        m14 = m14.replace("]", "")
        m14 = m14.replace("'", "")
        m14 = m14.replace(",", "")
        m15 = str(m15)
        m15 = m15.replace("[", "")
        m15 = m15.replace("]", "")
        m15 = m15.replace("'", "")
        m15 = m15.replace(",", "")
        m3 = str(m3)
        m3 = m3.replace("[", "")
        m3 = m3.replace("]", "")
        m3 = m3.replace("'", "")
        m3 = m3.replace(",", "")
        e.write(m1)
        e.write("\n")
        e.write(m2)
        e.write("\n")
        e.write(m3)
        e.write("\n")
        e.write(m4)
        e.write("\n")
        e.write(m5)
        e.write("\n")
        e.write(m6)
        e.write("\n")
        e.write(m7)
        e.write("\n")
        e.write(m8)
        e.write("\n")
        e.write(m9)
        e.write("\n")
        e.write(m10)
        e.write("\n")
        e.write(m11)
        e.write("\n")
        e.write(m12)
        e.write("\n")
        e.write(m13)
        e.write("\n")
        e.write(m14)
        e.write("\n")
        e.write(m15)
        e.close()
    elif item == "Acer Business":
        m8 = list(m8)
        m8.append(invertory)
        e = open("Models.txt", "w")
        m1 = str(m1)
        m1 = m1.replace("[", "")
        m1 = m1.replace("]", "")
        m1 = m1.replace("'", "")
        m1 = m1.replace(",", "")
        m2 = str(m2)
        m2 = m2.replace("[", "")
        m2 = m2.replace("]", "")
        m2 = m2.replace("'", "")
        m2 = m2.replace(",", "")
        m4 = str(m4)
        m4 = m4.replace("[", "")
        m4 = m4.replace("]", "")
        m4 = m4.replace("'", "")
        m4 = m4.replace(",", "")
        m5 = str(m5)
        m5 = m5.replace("[", "")
        m5 = m5.replace("]", "")
        m5 = m5.replace("'", "")
        m5 = m5.replace(",", "")
        m6 = str(m6)
        m6 = m6.replace("[", "")
        m6 = m6.replace("]", "")
        m6 = m6.replace("'", "")
        m6 = m6.replace(",", "")
        m7 = str(m7)
        m7 = m7.replace("[", "")
        m7 = m7.replace("]", "")
        m7 = m7.replace("'", "")
        m7 = m7.replace(",", "")
        m8 = str(m8)
        m8 = m8.replace("[", "")
        m8 = m8.replace("]", "")
        m8 = m8.replace("'", "")
        m8 = m8.replace(",", "")
        m9 = str(m9)
        m9 = m9.replace("[", "")
        m9 = m9.replace("]", "")
        m9 = m9.replace("'", "")
        m9 = m9.replace(",", "")
        m10 = str(m10)
        m10 = m10.replace("[", "")
        m10 = m10.replace("]", "")
        m10 = m10.replace("'", "")
        m10 = m10.replace(",", "")
        m11 = str(m11)
        m11 = m11.replace("[", "")
        m11 = m11.replace("]", "")
        m11 = m11.replace("'", "")
        m11 = m11.replace(",", "")
        m12 = str(m12)
        m12 = m12.replace("[", "")
        m12 = m12.replace("]", "")
        m12 = m12.replace("'", "")
        m12 = m12.replace(",", "")
        m13 = str(m13)
        m13 = m13.replace("[", "")
        m13 = m13.replace("]", "")
        m13 = m13.replace("'", "")
        m13 = m13.replace(",", "")
        m14 = str(m14)
        m14 = m14.replace("[", "")
        m14 = m14.replace("]", "")
        m14 = m14.replace("'", "")
        m14 = m14.replace(",", "")
        m15 = str(m15)
        m15 = m15.replace("[", "")
        m15 = m15.replace("]", "")
        m15 = m15.replace("'", "")
        m15 = m15.replace(",", "")
        m3 = str(m3)
        m3 = m3.replace("[", "")
        m3 = m3.replace("]", "")
        m3 = m3.replace("'", "")
        m3 = m3.replace(",", "")
        e.write(m1)
        e.write("\n")
        e.write(m2)
        e.write("\n")
        e.write(m3)
        e.write("\n")
        e.write(m4)
        e.write("\n")
        e.write(m5)
        e.write("\n")
        e.write(m6)
        e.write("\n")
        e.write(m7)
        e.write("\n")
        e.write(m8)
        e.write("\n")
        e.write(m9)
        e.write("\n")
        e.write(m10)
        e.write("\n")
        e.write(m11)
        e.write("\n")
        e.write(m12)
        e.write("\n")
        e.write(m13)
        e.write("\n")
        e.write(m14)
        e.write("\n")
        e.write(m15)
        e.close()
    elif item == "Asus Gaming":
        m9 = list(m9)
        m9.append(invertory)
        e = open("Models.txt", "w")
        m1 = str(m1)
        m1 = m1.replace("[", "")
        m1 = m1.replace("]", "")
        m1 = m1.replace("'", "")
        m1 = m1.replace(",", "")
        m2 = str(m2)
        m2 = m2.replace("[", "")
        m2 = m2.replace("]", "")
        m2 = m2.replace("'", "")
        m2 = m2.replace(",", "")
        m4 = str(m4)
        m4 = m4.replace("[", "")
        m4 = m4.replace("]", "")
        m4 = m4.replace("'", "")
        m4 = m4.replace(",", "")
        m5 = str(m5)
        m5 = m5.replace("[", "")
        m5 = m5.replace("]", "")
        m5 = m5.replace("'", "")
        m5 = m5.replace(",", "")
        m6 = str(m6)
        m6 = m6.replace("[", "")
        m6 = m6.replace("]", "")
        m6 = m6.replace("'", "")
        m6 = m6.replace(",", "")
        m7 = str(m7)
        m7 = m7.replace("[", "")
        m7 = m7.replace("]", "")
        m7 = m7.replace("'", "")
        m7 = m7.replace(",", "")
        m8 = str(m8)
        m8 = m8.replace("[", "")
        m8 = m8.replace("]", "")
        m8 = m8.replace("'", "")
        m8 = m8.replace(",", "")
        m9 = str(m9)
        m9 = m9.replace("[", "")
        m9 = m9.replace("]", "")
        m9 = m9.replace("'", "")
        m9 = m9.replace(",", "")
        m10 = str(m10)
        m10 = m10.replace("[", "")
        m10 = m10.replace("]", "")
        m10 = m10.replace("'", "")
        m10 = m10.replace(",", "")
        m11 = str(m11)
        m11 = m11.replace("[", "")
        m11 = m11.replace("]", "")
        m11 = m11.replace("'", "")
        m11 = m11.replace(",", "")
        m12 = str(m12)
        m12 = m12.replace("[", "")
        m12 = m12.replace("]", "")
        m12 = m12.replace("'", "")
        m12 = m12.replace(",", "")
        m13 = str(m13)
        m13 = m13.replace("[", "")
        m13 = m13.replace("]", "")
        m13 = m13.replace("'", "")
        m13 = m13.replace(",", "")
        m14 = str(m14)
        m14 = m14.replace("[", "")
        m14 = m14.replace("]", "")
        m14 = m14.replace("'", "")
        m14 = m14.replace(",", "")
        m15 = str(m15)
        m15 = m15.replace("[", "")
        m15 = m15.replace("]", "")
        m15 = m15.replace("'", "")
        m15 = m15.replace(",", "")
        m3 = str(m3)
        m3 = m3.replace("[", "")
        m3 = m3.replace("]", "")
        m3 = m3.replace("'", "")
        m3 = m3.replace(",", "")
        e.write(m1)
        e.write("\n")
        e.write(m2)
        e.write("\n")
        e.write(m3)
        e.write("\n")
        e.write(m4)
        e.write("\n")
        e.write(m5)
        e.write("\n")
        e.write(m6)
        e.write("\n")
        e.write(m7)
        e.write("\n")
        e.write(m8)
        e.write("\n")
        e.write(m9)
        e.write("\n")
        e.write(m10)
        e.write("\n")
        e.write(m11)
        e.write("\n")
        e.write(m12)
        e.write("\n")
        e.write(m13)
        e.write("\n")
        e.write(m14)
        e.write("\n")
        e.write(m15)
        e.close()
    elif item == "Asus Business":
        m10 = list(m10)
        m10.append(invertory)
        e = open("Models.txt", "w")
        m1 = str(m1)
        m1 = m1.replace("[", "")
        m1 = m1.replace("]", "")
        m1 = m1.replace("'", "")
        m1 = m1.replace(",", "")
        m2 = str(m2)
        m2 = m2.replace("[", "")
        m2 = m2.replace("]", "")
        m2 = m2.replace("'", "")
        m2 = m2.replace(",", "")
        m4 = str(m4)
        m4 = m4.replace("[", "")
        m4 = m4.replace("]", "")
        m4 = m4.replace("'", "")
        m4 = m4.replace(",", "")
        m5 = str(m5)
        m5 = m5.replace("[", "")
        m5 = m5.replace("]", "")
        m5 = m5.replace("'", "")
        m5 = m5.replace(",", "")
        m6 = str(m6)
        m6 = m6.replace("[", "")
        m6 = m6.replace("]", "")
        m6 = m6.replace("'", "")
        m6 = m6.replace(",", "")
        m7 = str(m7)
        m7 = m7.replace("[", "")
        m7 = m7.replace("]", "")
        m7 = m7.replace("'", "")
        m7 = m7.replace(",", "")
        m8 = str(m8)
        m8 = m8.replace("[", "")
        m8 = m8.replace("]", "")
        m8 = m8.replace("'", "")
        m8 = m8.replace(",", "")
        m9 = str(m9)
        m9 = m9.replace("[", "")
        m9 = m9.replace("]", "")
        m9 = m9.replace("'", "")
        m9 = m9.replace(",", "")
        m10 = str(m10)
        m10 = m10.replace("[", "")
        m10 = m10.replace("]", "")
        m10 = m10.replace("'", "")
        m10 = m10.replace(",", "")
        m11 = str(m11)
        m11 = m11.replace("[", "")
        m11 = m11.replace("]", "")
        m11 = m11.replace("'", "")
        m11 = m11.replace(",", "")
        m12 = str(m12)
        m12 = m12.replace("[", "")
        m12 = m12.replace("]", "")
        m12 = m12.replace("'", "")
        m12 = m12.replace(",", "")
        m13 = str(m13)
        m13 = m13.replace("[", "")
        m13 = m13.replace("]", "")
        m13 = m13.replace("'", "")
        m13 = m13.replace(",", "")
        m14 = str(m14)
        m14 = m14.replace("[", "")
        m14 = m14.replace("]", "")
        m14 = m14.replace("'", "")
        m14 = m14.replace(",", "")
        m15 = str(m15)
        m15 = m15.replace("[", "")
        m15 = m15.replace("]", "")
        m15 = m15.replace("'", "")
        m15 = m15.replace(",", "")
        m3 = str(m3)
        m3 = m3.replace("[", "")
        m3 = m3.replace("]", "")
        m3 = m3.replace("'", "")
        m3 = m3.replace(",", "")
        e.write(m1)
        e.write("\n")
        e.write(m2)
        e.write("\n")
        e.write(m3)
        e.write("\n")
        e.write(m4)
        e.write("\n")
        e.write(m5)
        e.write("\n")
        e.write(m6)
        e.write("\n")
        e.write(m7)
        e.write("\n")
        e.write(m8)
        e.write("\n")
        e.write(m9)
        e.write("\n")
        e.write(m10)
        e.write("\n")
        e.write(m11)
        e.write("\n")
        e.write(m12)
        e.write("\n")
        e.write(m13)
        e.write("\n")
        e.write(m14)
        e.write("\n")
        e.write(m15)
        e.close()
    elif item == "Apple":
        m11 = list(m11)
        m11.append(invertory)
        e = open("Models.txt", "w")
        m1 = str(m1)
        m1 = m1.replace("[", "")
        m1 = m1.replace("]", "")
        m1 = m1.replace("'", "")
        m1 = m1.replace(",", "")
        m2 = str(m2)
        m2 = m2.replace("[", "")
        m2 = m2.replace("]", "")
        m2 = m2.replace("'", "")
        m2 = m2.replace(",", "")
        m4 = str(m4)
        m4 = m4.replace("[", "")
        m4 = m4.replace("]", "")
        m4 = m4.replace("'", "")
        m4 = m4.replace(",", "")
        m5 = str(m5)
        m5 = m5.replace("[", "")
        m5 = m5.replace("]", "")
        m5 = m5.replace("'", "")
        m5 = m5.replace(",", "")
        m6 = str(m6)
        m6 = m6.replace("[", "")
        m6 = m6.replace("]", "")
        m6 = m6.replace("'", "")
        m6 = m6.replace(",", "")
        m7 = str(m7)
        m7 = m7.replace("[", "")
        m7 = m7.replace("]", "")
        m7 = m7.replace("'", "")
        m7 = m7.replace(",", "")
        m8 = str(m8)
        m8 = m8.replace("[", "")
        m8 = m8.replace("]", "")
        m8 = m8.replace("'", "")
        m8 = m8.replace(",", "")
        m9 = str(m9)
        m9 = m9.replace("[", "")
        m9 = m9.replace("]", "")
        m9 = m9.replace("'", "")
        m9 = m9.replace(",", "")
        m10 = str(m10)
        m10 = m10.replace("[", "")
        m10 = m10.replace("]", "")
        m10 = m10.replace("'", "")
        m10 = m10.replace(",", "")
        m11 = str(m11)
        m11 = m11.replace("[", "")
        m11 = m11.replace("]", "")
        m11 = m11.replace("'", "")
        m11 = m11.replace(",", "")
        m12 = str(m12)
        m12 = m12.replace("[", "")
        m12 = m12.replace("]", "")
        m12 = m12.replace("'", "")
        m12 = m12.replace(",", "")
        m13 = str(m13)
        m13 = m13.replace("[", "")
        m13 = m13.replace("]", "")
        m13 = m13.replace("'", "")
        m13 = m13.replace(",", "")
        m14 = str(m14)
        m14 = m14.replace("[", "")
        m14 = m14.replace("]", "")
        m14 = m14.replace("'", "")
        m14 = m14.replace(",", "")
        m15 = str(m15)
        m15 = m15.replace("[", "")
        m15 = m15.replace("]", "")
        m15 = m15.replace("'", "")
        m15 = m15.replace(",", "")
        m3 = str(m3)
        m3 = m3.replace("[", "")
        m3 = m3.replace("]", "")
        m3 = m3.replace("'", "")
        m3 = m3.replace(",", "")
        e.write(m1)
        e.write("\n")
        e.write(m2)
        e.write("\n")
        e.write(m3)
        e.write("\n")
        e.write(m4)
        e.write("\n")
        e.write(m5)
        e.write("\n")
        e.write(m6)
        e.write("\n")
        e.write(m7)
        e.write("\n")
        e.write(m8)
        e.write("\n")
        e.write(m9)
        e.write("\n")
        e.write(m10)
        e.write("\n")
        e.write(m11)
        e.write("\n")
        e.write(m12)
        e.write("\n")
        e.write(m13)
        e.write("\n")
        e.write(m14)
        e.write("\n")
        e.write(m15)
        e.close()
    elif item == "Huawei":
        m12 = list(m12)
        m12.append(invertory)
        e = open("Models.txt", "w")
        m1 = str(m1)
        m1 = m1.replace("[", "")
        m1 = m1.replace("]", "")
        m1 = m1.replace("'", "")
        m1 = m1.replace(",", "")
        m2 = str(m2)
        m2 = m2.replace("[", "")
        m2 = m2.replace("]", "")
        m2 = m2.replace("'", "")
        m2 = m2.replace(",", "")
        m4 = str(m4)
        m4 = m4.replace("[", "")
        m4 = m4.replace("]", "")
        m4 = m4.replace("'", "")
        m4 = m4.replace(",", "")
        m5 = str(m5)
        m5 = m5.replace("[", "")
        m5 = m5.replace("]", "")
        m5 = m5.replace("'", "")
        m5 = m5.replace(",", "")
        m6 = str(m6)
        m6 = m6.replace("[", "")
        m6 = m6.replace("]", "")
        m6 = m6.replace("'", "")
        m6 = m6.replace(",", "")
        m7 = str(m7)
        m7 = m7.replace("[", "")
        m7 = m7.replace("]", "")
        m7 = m7.replace("'", "")
        m7 = m7.replace(",", "")
        m8 = str(m8)
        m8 = m8.replace("[", "")
        m8 = m8.replace("]", "")
        m8 = m8.replace("'", "")
        m8 = m8.replace(",", "")
        m9 = str(m9)
        m9 = m9.replace("[", "")
        m9 = m9.replace("]", "")
        m9 = m9.replace("'", "")
        m9 = m9.replace(",", "")
        m10 = str(m10)
        m10 = m10.replace("[", "")
        m10 = m10.replace("]", "")
        m10 = m10.replace("'", "")
        m10 = m10.replace(",", "")
        m11 = str(m11)
        m11 = m11.replace("[", "")
        m11 = m11.replace("]", "")
        m11 = m11.replace("'", "")
        m11 = m11.replace(",", "")
        m12 = str(m12)
        m12 = m12.replace("[", "")
        m12 = m12.replace("]", "")
        m12 = m12.replace("'", "")
        m12 = m12.replace(",", "")
        m13 = str(m13)
        m13 = m13.replace("[", "")
        m13 = m13.replace("]", "")
        m13 = m13.replace("'", "")
        m13 = m13.replace(",", "")
        m14 = str(m14)
        m14 = m14.replace("[", "")
        m14 = m14.replace("]", "")
        m14 = m14.replace("'", "")
        m14 = m14.replace(",", "")
        m15 = str(m15)
        m15 = m15.replace("[", "")
        m15 = m15.replace("]", "")
        m15 = m15.replace("'", "")
        m15 = m15.replace(",", "")
        m3 = str(m3)
        m3 = m3.replace("[", "")
        m3 = m3.replace("]", "")
        m3 = m3.replace("'", "")
        m3 = m3.replace(",", "")
        e.write(m1)
        e.write("\n")
        e.write(m2)
        e.write("\n")
        e.write(m3)
        e.write("\n")
        e.write(m4)
        e.write("\n")
        e.write(m5)
        e.write("\n")
        e.write(m6)
        e.write("\n")
        e.write(m7)
        e.write("\n")
        e.write(m8)
        e.write("\n")
        e.write(m9)
        e.write("\n")
        e.write(m10)
        e.write("\n")
        e.write(m11)
        e.write("\n")
        e.write(m12)
        e.write("\n")
        e.write(m13)
        e.write("\n")
        e.write(m14)
        e.write("\n")
        e.write(m15)
        e.close()
    elif item == "MSI Gaming":
        m13 = list(m13)
        m13.append(invertory)
        e = open("Models.txt", "w")
        m1 = str(m1)
        m1 = m1.replace("[", "")
        m1 = m1.replace("]", "")
        m1 = m1.replace("'", "")
        m1 = m1.replace(",", "")
        m2 = str(m2)
        m2 = m2.replace("[", "")
        m2 = m2.replace("]", "")
        m2 = m2.replace("'", "")
        m2 = m2.replace(",", "")
        m4 = str(m4)
        m4 = m4.replace("[", "")
        m4 = m4.replace("]", "")
        m4 = m4.replace("'", "")
        m4 = m4.replace(",", "")
        m5 = str(m5)
        m5 = m5.replace("[", "")
        m5 = m5.replace("]", "")
        m5 = m5.replace("'", "")
        m5 = m5.replace(",", "")
        m6 = str(m6)
        m6 = m6.replace("[", "")
        m6 = m6.replace("]", "")
        m6 = m6.replace("'", "")
        m6 = m6.replace(",", "")
        m7 = str(m7)
        m7 = m7.replace("[", "")
        m7 = m7.replace("]", "")
        m7 = m7.replace("'", "")
        m7 = m7.replace(",", "")
        m8 = str(m8)
        m8 = m8.replace("[", "")
        m8 = m8.replace("]", "")
        m8 = m8.replace("'", "")
        m8 = m8.replace(",", "")
        m9 = str(m9)
        m9 = m9.replace("[", "")
        m9 = m9.replace("]", "")
        m9 = m9.replace("'", "")
        m9 = m9.replace(",", "")
        m10 = str(m10)
        m10 = m10.replace("[", "")
        m10 = m10.replace("]", "")
        m10 = m10.replace("'", "")
        m10 = m10.replace(",", "")
        m11 = str(m11)
        m11 = m11.replace("[", "")
        m11 = m11.replace("]", "")
        m11 = m11.replace("'", "")
        m11 = m11.replace(",", "")
        m12 = str(m12)
        m12 = m12.replace("[", "")
        m12 = m12.replace("]", "")
        m12 = m12.replace("'", "")
        m12 = m12.replace(",", "")
        m13 = str(m13)
        m13 = m13.replace("[", "")
        m13 = m13.replace("]", "")
        m13 = m13.replace("'", "")
        m13 = m13.replace(",", "")
        m14 = str(m14)
        m14 = m14.replace("[", "")
        m14 = m14.replace("]", "")
        m14 = m14.replace("'", "")
        m14 = m14.replace(",", "")
        m15 = str(m15)
        m15 = m15.replace("[", "")
        m15 = m15.replace("]", "")
        m15 = m15.replace("'", "")
        m15 = m15.replace(",", "")
        m3 = str(m3)
        m3 = m3.replace("[", "")
        m3 = m3.replace("]", "")
        m3 = m3.replace("'", "")
        m3 = m3.replace(",", "")
        e.write(m1)
        e.write("\n")
        e.write(m2)
        e.write("\n")
        e.write(m3)
        e.write("\n")
        e.write(m4)
        e.write("\n")
        e.write(m5)
        e.write("\n")
        e.write(m6)
        e.write("\n")
        e.write(m7)
        e.write("\n")
        e.write(m8)
        e.write("\n")
        e.write(m9)
        e.write("\n")
        e.write(m10)
        e.write("\n")
        e.write(m11)
        e.write("\n")
        e.write(m12)
        e.write("\n")
        e.write(m13)
        e.write("\n")
        e.write(m14)
        e.write("\n")
        e.write(m15)
        e.close()
    elif item == "MSI Business":
        m14 = list(m14)
        m14.append(invertory)
        e = open("Models.txt", "w")
        m1 = str(m1)
        m1 = m1.replace("[", "")
        m1 = m1.replace("]", "")
        m1 = m1.replace("'", "")
        m1 = m1.replace(",", "")
        m2 = str(m2)
        m2 = m2.replace("[", "")
        m2 = m2.replace("]", "")
        m2 = m2.replace("'", "")
        m2 = m2.replace(",", "")
        m4 = str(m4)
        m4 = m4.replace("[", "")
        m4 = m4.replace("]", "")
        m4 = m4.replace("'", "")
        m4 = m4.replace(",", "")
        m5 = str(m5)
        m5 = m5.replace("[", "")
        m5 = m5.replace("]", "")
        m5 = m5.replace("'", "")
        m5 = m5.replace(",", "")
        m6 = str(m6)
        m6 = m6.replace("[", "")
        m6 = m6.replace("]", "")
        m6 = m6.replace("'", "")
        m6 = m6.replace(",", "")
        m7 = str(m7)
        m7 = m7.replace("[", "")
        m7 = m7.replace("]", "")
        m7 = m7.replace("'", "")
        m7 = m7.replace(",", "")
        m8 = str(m8)
        m8 = m8.replace("[", "")
        m8 = m8.replace("]", "")
        m8 = m8.replace("'", "")
        m8 = m8.replace(",", "")
        m9 = str(m9)
        m9 = m9.replace("[", "")
        m9 = m9.replace("]", "")
        m9 = m9.replace("'", "")
        m9 = m9.replace(",", "")
        m10 = str(m10)
        m10 = m10.replace("[", "")
        m10 = m10.replace("]", "")
        m10 = m10.replace("'", "")
        m10 = m10.replace(",", "")
        m11 = str(m11)
        m11 = m11.replace("[", "")
        m11 = m11.replace("]", "")
        m11 = m11.replace("'", "")
        m11 = m11.replace(",", "")
        m12 = str(m12)
        m12 = m12.replace("[", "")
        m12 = m12.replace("]", "")
        m12 = m12.replace("'", "")
        m12 = m12.replace(",", "")
        m13 = str(m13)
        m13 = m13.replace("[", "")
        m13 = m13.replace("]", "")
        m13 = m13.replace("'", "")
        m13 = m13.replace(",", "")
        m14 = str(m14)
        m14 = m14.replace("[", "")
        m14 = m14.replace("]", "")
        m14 = m14.replace("'", "")
        m14 = m14.replace(",", "")
        m15 = str(m15)
        m15 = m15.replace("[", "")
        m15 = m15.replace("]", "")
        m15 = m15.replace("'", "")
        m15 = m15.replace(",", "")
        m3 = str(m3)
        m3 = m3.replace("[", "")
        m3 = m3.replace("]", "")
        m3 = m3.replace("'", "")
        m3 = m3.replace(",", "")
        e.write(m1)
        e.write("\n")
        e.write(m2)
        e.write("\n")
        e.write(m3)
        e.write("\n")
        e.write(m4)
        e.write("\n")
        e.write(m5)
        e.write("\n")
        e.write(m6)
        e.write("\n")
        e.write(m7)
        e.write("\n")
        e.write(m8)
        e.write("\n")
        e.write(m9)
        e.write("\n")
        e.write(m10)
        e.write("\n")
        e.write(m11)
        e.write("\n")
        e.write(m12)
        e.write("\n")
        e.write(m13)
        e.write("\n")
        e.write(m14)
        e.write("\n")
        e.write(m15)
        e.close()
    elif item == "Microsoft":
        m15 = list(m15)
        m15.append(invertory)
        e = open("Models.txt", "w")
        m1 = str(m1)
        m1 = m1.replace("[", "")
        m1 = m1.replace("]", "")
        m1 = m1.replace("'", "")
        m1 = m1.replace(",", "")
        m2 = str(m2)
        m2 = m2.replace("[", "")
        m2 = m2.replace("]", "")
        m2 = m2.replace("'", "")
        m2 = m2.replace(",", "")
        m4 = str(m4)
        m4 = m4.replace("[", "")
        m4 = m4.replace("]", "")
        m4 = m4.replace("'", "")
        m4 = m4.replace(",", "")
        m5 = str(m5)
        m5 = m5.replace("[", "")
        m5 = m5.replace("]", "")
        m5 = m5.replace("'", "")
        m5 = m5.replace(",", "")
        m6 = str(m6)
        m6 = m6.replace("[", "")
        m6 = m6.replace("]", "")
        m6 = m6.replace("'", "")
        m6 = m6.replace(",", "")
        m7 = str(m7)
        m7 = m7.replace("[", "")
        m7 = m7.replace("]", "")
        m7 = m7.replace("'", "")
        m7 = m7.replace(",", "")
        m8 = str(m8)
        m8 = m8.replace("[", "")
        m8 = m8.replace("]", "")
        m8 = m8.replace("'", "")
        m8 = m8.replace(",", "")
        m9 = str(m9)
        m9 = m9.replace("[", "")
        m9 = m9.replace("]", "")
        m9 = m9.replace("'", "")
        m9 = m9.replace(",", "")
        m10 = str(m10)
        m10 = m10.replace("[", "")
        m10 = m10.replace("]", "")
        m10 = m10.replace("'", "")
        m10 = m10.replace(",", "")
        m11 = str(m11)
        m11 = m11.replace("[", "")
        m11 = m11.replace("]", "")
        m11 = m11.replace("'", "")
        m11 = m11.replace(",", "")
        m12 = str(m12)
        m12 = m12.replace("[", "")
        m12 = m12.replace("]", "")
        m12 = m12.replace("'", "")
        m12 = m12.replace(",", "")
        m13 = str(m13)
        m13 = m13.replace("[", "")
        m13 = m13.replace("]", "")
        m13 = m13.replace("'", "")
        m13 = m13.replace(",", "")
        m14 = str(m14)
        m14 = m14.replace("[", "")
        m14 = m14.replace("]", "")
        m14 = m14.replace("'", "")
        m14 = m14.replace(",", "")
        m15 = str(m15)
        m15 = m15.replace("[", "")
        m15 = m15.replace("]", "")
        m15 = m15.replace("'", "")
        m15 = m15.replace(",", "")
        m3 = str(m3)
        m3 = m3.replace("[", "")
        m3 = m3.replace("]", "")
        m3 = m3.replace("'", "")
        m3 = m3.replace(",", "")
        e.write(m1)
        e.write("\n")
        e.write(m2)
        e.write("\n")
        e.write(m3)
        e.write("\n")
        e.write(m4)
        e.write("\n")
        e.write(m5)
        e.write("\n")
        e.write(m6)
        e.write("\n")
        e.write(m7)
        e.write("\n")
        e.write(m8)
        e.write("\n")
        e.write(m9)
        e.write("\n")
        e.write(m10)
        e.write("\n")
        e.write(m11)
        e.write("\n")
        e.write(m12)
        e.write("\n")
        e.write(m13)
        e.write("\n")
        e.write(m14)
        e.write("\n")
        e.write(m15)
        e.close()
    elif item == "bags":
        e1 = list(e1)
        print(e1)
        e1.append(invertory)
        r = open("Project[accessories].txt", "w")
        e1 = str(e1)
        e1 = e1.replace("[", "")
        e1 = e1.replace("'", "")
        e1 = e1.replace("]", "")
        e1 = e1.replace(",", "")
        e2 = str(e2)
        e2 = e2.replace("[", "")
        e2 = e2.replace("'", "")
        e2 = e2.replace("]", "")
        e2 = e2.replace(",", "")
        e3 = str(e3)
        e3 = e3.replace("[", "")
        e3 = e3.replace("'", "")
        e3 = e3.replace("]", "")
        e3 = e3.replace(",", "")
        e4 = str(e4)
        e4 = e4.replace("[", "")
        e4 = e4.replace("'", "")
        e4 = e4.replace("]", "")
        e4 = e4.replace(",", "")
        e5 = str(e5)
        e5 = e5.replace("[", "")
        e5 = e5.replace("'", "")
        e5 = e5.replace("]", "")
        e5 = e5.replace(",", "")
        e6 = str(e6)
        e6 = e6.replace("[", "")
        e6 = e6.replace("'", "")
        e6 = e6.replace("]", "")
        e6 = e6.replace(",", "")
        r.write(e1)
        r.write("\n")
        r.write(e2)
        r.write("\n")
        r.write(e3)
        r.write("\n")
        r.write(e4)
        r.write("\n")
        r.write(e5)
        r.write("\n")
        r.write(e6)
        r.close()
    elif item == "skins":
        e2 = list(e2)
        print(e2)
        e2.append(invertory)
        r = open("Project[accessories].txt", "w")
        e1 = str(e1)
        e1 = e1.replace("[", "")
        e1 = e1.replace("'", "")
        e1 = e1.replace("]", "")
        e1 = e1.replace(",", "")
        e2 = str(e2)
        e2 = e2.replace("[", "")
        e2 = e2.replace("'", "")
        e2 = e2.replace("]", "")
        e2 = e2.replace(",", "")
        e3 = str(e3)
        e3 = e3.replace("[", "")
        e3 = e3.replace("'", "")
        e3 = e3.replace("]", "")
        e3 = e3.replace(",", "")
        e4 = str(e4)
        e4 = e4.replace("[", "")
        e4 = e4.replace("'", "")
        e4 = e4.replace("]", "")
        e4 = e4.replace(",", "")
        e5 = str(e5)
        e5 = e5.replace("[", "")
        e5 = e5.replace("'", "")
        e5 = e5.replace("]", "")
        e5 = e5.replace(",", "")
        e6 = str(e6)
        e6 = e6.replace("[", "")
        e6 = e6.replace("'", "")
        e6 = e6.replace("]", "")
        e6 = e6.replace(",", "")
        r.write(e1)
        r.write("\n")
        r.write(e2)
        r.write("\n")
        r.write(e3)
        r.write("\n")
        r.write(e4)
        r.write("\n")
        r.write(e5)
        r.write("\n")
        r.write(e6)
        r.close()
    elif item == "product":
        e3 = list(e3)
        print(e3)
        e3.append(invertory)
        r = open("Project[accessories].txt", "w")
        e1 = str(e1)
        e1 = e1.replace("[", "")
        e1 = e1.replace("'", "")
        e1 = e1.replace("]", "")
        e1 = e1.replace(",", "")
        e2 = str(e2)
        e2 = e2.replace("[", "")
        e2 = e2.replace("'", "")
        e2 = e2.replace("]", "")
        e2 = e2.replace(",", "")
        e3 = str(e3)
        e3 = e3.replace("[", "")
        e3 = e3.replace("'", "")
        e3 = e3.replace("]", "")
        e3 = e3.replace(",", "")
        e4 = str(e4)
        e4 = e4.replace("[", "")
        e4 = e4.replace("'", "")
        e4 = e4.replace("]", "")
        e4 = e4.replace(",", "")
        e5 = str(e5)
        e5 = e5.replace("[", "")
        e5 = e5.replace("'", "")
        e5 = e5.replace("]", "")
        e5 = e5.replace(",", "")
        e6 = str(e6)
        e6 = e6.replace("[", "")
        e6 = e6.replace("'", "")
        e6 = e6.replace("]", "")
        e6 = e6.replace(",", "")
        r.write(e1)
        r.write("\n")
        r.write(e2)
        r.write("\n")
        r.write(e3)
        r.write("\n")
        r.write(e4)
        r.write("\n")
        r.write(e5)
        r.write("\n")
        r.write(e6)
        r.close()
    elif item == "mouses":
        e4 = list(e4)
        print(e4)
        e4.append(invertory)
        r = open("Project[accessories].txt", "w")
        e1 = str(e1)
        e1 = e1.replace("[", "")
        e1 = e1.replace("'", "")
        e1 = e1.replace("]", "")
        e1 = e1.replace(",", "")
        e2 = str(e2)
        e2 = e2.replace("[", "")
        e2 = e2.replace("'", "")
        e2 = e2.replace("]", "")
        e2 = e2.replace(",", "")
        e3 = str(e3)
        e3 = e3.replace("[", "")
        e3 = e3.replace("'", "")
        e3 = e3.replace("]", "")
        e3 = e3.replace(",", "")
        e4 = str(e4)
        e4 = e4.replace("[", "")
        e4 = e4.replace("'", "")
        e4 = e4.replace("]", "")
        e4 = e4.replace(",", "")
        e5 = str(e5)
        e5 = e5.replace("[", "")
        e5 = e5.replace("'", "")
        e5 = e5.replace("]", "")
        e5 = e5.replace(",", "")
        e6 = str(e6)
        e6 = e6.replace("[", "")
        e6 = e6.replace("'", "")
        e6 = e6.replace("]", "")
        e6 = e6.replace(",", "")
        r.write(e1)
        r.write("\n")
        r.write(e2)
        r.write("\n")
        r.write(e3)
        r.write("\n")
        r.write(e4)
        r.write("\n")
        r.write(e5)
        r.write("\n")
        r.write(e6)
        r.close()
    elif item == "stand holders":
        e5 = list(e5)
        print(e5)
        e5.append(invertory)
        r = open("Project[accessories].txt", "w")
        e1 = str(e1)
        e1 = e1.replace("[", "")
        e1 = e1.replace("'", "")
        e1 = e1.replace("]", "")
        e1 = e1.replace(",", "")
        e2 = str(e2)
        e2 = e2.replace("[", "")
        e2 = e2.replace("'", "")
        e2 = e2.replace("]", "")
        e2 = e2.replace(",", "")
        e3 = str(e3)
        e3 = e3.replace("[", "")
        e3 = e3.replace("'", "")
        e3 = e3.replace("]", "")
        e3 = e3.replace(",", "")
        e4 = str(e4)
        e4 = e4.replace("[", "")
        e4 = e4.replace("'", "")
        e4 = e4.replace("]", "")
        e4 = e4.replace(",", "")
        e5 = str(e5)
        e5 = e5.replace("[", "")
        e5 = e5.replace("'", "")
        e5 = e5.replace("]", "")
        e5 = e5.replace(",", "")
        e6 = str(e6)
        e6 = e6.replace("[", "")
        e6 = e6.replace("'", "")
        e6 = e6.replace("]", "")
        e6 = e6.replace(",", "")
        r.write(e1)
        r.write("\n")
        r.write(e2)
        r.write("\n")
        r.write(e3)
        r.write("\n")
        r.write(e4)
        r.write("\n")
        r.write(e5)
        r.write("\n")
        r.write(e6)
        r.close()
    elif item == "laptop tables":
        e6 = list(e6)
        print(e6)
        e6.append(invertory)
        print(e6)
        r = open("Project[accessories].txt", "w")
        e1 = str(e1)
        e1 = e1.replace("[", "")
        e1 = e1.replace("'", "")
        e1 = e1.replace("]", "")
        e1 = e1.replace(",", "")
        e2 = str(e2)
        e2 = e2.replace("[", "")
        e2 = e2.replace("'", "")
        e2 = e2.replace("]", "")
        e2 = e2.replace(",", "")
        e3 = str(e3)
        e3 = e3.replace("[", "")
        e3 = e3.replace("'", "")
        e3 = e3.replace("]", "")
        e3 = e3.replace(",", "")
        e4 = str(e4)
        e4 = e4.replace("[", "")
        e4 = e4.replace("'", "")
        e4 = e4.replace("]", "")
        e4 = e4.replace(",", "")
        e5 = str(e5)
        e5 = e5.replace("[", "")
        e5 = e5.replace("'", "")
        e5 = e5.replace("]", "")
        e5 = e5.replace(",", "")
        e6 = str(e6)
        e6 = e6.replace("[", "")
        e6 = e6.replace("'", "")
        e6 = e6.replace("]", "")
        e6 = e6.replace(",", "")
        r.write(e1)
        r.write("\n")
        r.write(e2)
        r.write("\n")
        r.write(e3)
        r.write("\n")
        r.write(e4)
        r.write("\n")
        r.write(e5)
        r.write("\n")
        r.write(e6)
        r.close()
    else:
        item = input("this item doesn't excist, try again :")
        accsfile.close()


# seller(input("Enter Product"))
accountchecker = input("Welcome to laptop corner store! \nWrite 1 to login ,2 to create account, 3 to reset password.,4 to login as seller.")
if accountchecker == "1":
    readaccount(input("Enter Account"), input("Enter Password"))
    random_list()
    laprandom()
    search = input("1.Search for laptop\n2.for Accesories.")
    if search == "1":
        lapsortedby(input("Enter brand:"))
    elif search == "2":
        accs_sortedby("Enter Category:")
    buy = input("Want any product?Y/N")
    if buy == "Y":
        product = input("write product:")
        location(input("Enter City:"), input("Enter area:"), input("Enter street:(landmark(optional))"), input("Enter building:"), input("Enter Floor:"), input("Enter apartment:"))
        paymethod = input("1.Cash, 2.Visa")
        if paymethod == "1":
            print("Payment method cash selected")
        elif paymethod == "2":
            print("Visa payment method selected.")
            visadata(input("Enter 16-digit number:"))
        print(product, "is ordered and will deliver in 3 days\nThank You for choosing Laptop corner store\nHave a nice day!")
    elif buy == "N":
        print("have a nice day!")
elif accountchecker == "2":
    createaccount()
elif accountchecker == "3":
    forgetpassword(input("Enter Email:"))
elif accountchecker == "4":
    readaccount(input("Enter Account"), input("Enter Password:"))
    seller(input("Enter item to add"))
else:
    print("Not valid")
